[player_info]
player_name = "qjr" # Username which will be displayed in lobby

[address]
host_ip = "120.233.26.237" # The IP which will be broadcasted or connected to.
port = 47989          # host开放的port

[gamerule]
drain_when_hurt = true # 对战中，在任何玩家血量变化后是否清空所有玩家的点数
